plugin: amazon.aws.aws_ec2

regions:
  - "{{ lookup('env', 'AWS_REGION') | default('ap-southeast-1', true) }}"

filters:
  instance-state-name: running
  "tag:Project": project1
  "tag:Environment": dev
  "tag:Role": app

hostnames:
  - instance-id

compose:
  ansible_host: instance_id
  ansible_connection: "'amazon.aws.aws_ssm'"
  ansible_aws_ssm_region: "lookup('env', 'AWS_REGION') | default('ap-southeast-1', true)"
  ansible_aws_ssm_bucket_name: "lookup('env', 'ANSIBLE_SSM_BUCKET')"
  ansible_shell_type: "'sh'"
  ansible_user: "'ec2-user'"
  ansible_python_interpreter: "'/usr/bin/python3'"

keyed_groups:
  - key: tags.Role
    prefix: role
  - key: tags.Environment
    prefix: env

groups:
  app: tags.Role == 'app'