---
- name: Deploy Application
  hosts: all
  become: yes
  tasks:
    - name: Copy app.env template
      template:
        src: ../templates/app.env.j2
        dest: /home/ec2-user/.env
        owner: ec2-user
        group: ec2-user
        mode: '0600'

    - name: Pull and Run App Container
      shell: |
        docker pull nginx:latest
        docker run -d --name my-app -p 80:80 nginx:latest
      become_user: ec2-user
