---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name:
          - docker
          - git
        state: present
        update_cache: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
